#!/usr/bin/env bash

# deploy ssh key to a remote server
# places key on remote server
# sets up remote server to use keychain
# adds key to the keychain automatically at login by modifying bashrc

#example call:
# ssh-deploy mykey.pem my_ssh_config_host ubuntu mykey_to_put_on_server

host_key=~/.ssh/$1
host=$2
host_user=$3
key_name=$4
key_fqp=/home/$host_user/.ssh/$key_name

ssh-create -n $key_name

if [[ $? == 1 ]]; then
    echo "if you want to recreate the key, run ssh-remove first"
    exit 1
fi

scp -i $host_key ~/.ssh/$key_name $host:/home/$host_user/.ssh/
scp -i $host_key ~/.ssh/$key_name.pub $host:/home/$host_user/.ssh/

LINE='eval "\$(keychain --eval '$key_name')"'
FILE="/home/${host_user}/.bashrc"


# execute commands on remote server
ssh -t -i $host_key $host <<EOF
# set proper permissions on keys
chmod 600 $key_fqp
chmod 600 $key_fqp.pub

# create bashrc if it doesn't exist
touch ~/.bashrc
# install keychain, used to make sure ssh key is availabe for use at anytime
#sudo apt-get install keychain -y
grep -q -F "eychain --eval $key_name" "$FILE" || echo $LINE >> "$FILE"
EOF

cat ~/.ssh/$key_name.pub | xclip -sel clip
echo "$key_name.pub copied to clipboard."
